services:

## REVERSE PROXY
  nginx:
    container_name: transcendence-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: ["8080:80", "8443:443"]
    depends_on: [frontend, backend]
    volumes:
      - ./.certs/nginx/site.crt:/etc/nginx/certs/fullchain.pem:ro
      - ./.certs/nginx/site.key:/etc/nginx/certs/privkey.pem:ro
      - ./.certs/ca/ca.crt:/etc/nginx/certs/ca.crt:ro

## FRONTEND CONTAINER
  frontend:
    container_name: transcendence-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    expose:
      - "80"
    depends_on:
      - backend

## BACKEND CONTAINER
  backend:
    container_name: transcendence-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./backend/src/database:/app/database
      - ./.certs/backend:/certs:ro
    env_file:
      - .env
    command: npm start

