services:
## REVERSE PROXY
  nginx:
    container_name: transcendence-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: ["8080:80", "8443:443"]
    depends_on: [frontend, backend]

## FRONTEND CONTAINER
  frontend:
    container_name: transcendence-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    expose:
      - "80"
    #ports:
    #  - "${FRONTEND_PORT:-8080}:80"
    # env_file:
    #   - .env
    depends_on:
      - backend
## BACKEND CONTAINER
  backend:
    container_name: transcendence-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    #ports:
    #  - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    volumes:
    #   - ./backend/src:/app/src
      - ./backend/src/database:/app/database
    env_file:
      - .env
    environment:
      LAN_IP: ${LAN_IP}
    command: npm start
    # networks:
      # - app-network


# networks:
#   app-network:
#     driver: bridge
# volumes:
#   transcendence-db:
#       driver: local
