services:
## FRONTEND CONTAINER
  frontend:
    container_name: transcendence-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    env_file:
      - .env
    depends_on:
      - backend
## BACKEND CONTAINER
  backend:
    container_name: transcendence-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
    environment:
      - DEBUG=${DEBUG:-no}
      - BACKEND_PORT=${BACKEND_PORT:-3000}
      - BACKEND_HOST=${BACKEND_HOST:-0.0.0.0}
    env_file:
      - .env
    command: npm run dev
