services:
## FRONTEND CONTAINER
  frontend:
    container_name: transcendence-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      # - "${FRONTEND_PORT:-8080}:80"
      - "5173:5173" # FASE DE DESENVOLVIMENTO -> DELETE!!!!
    volumes: # FASE DE DESENVOLVIMENTO -> DELETE!!!!
      - ./frontend/src:/app/src
      - ./frontend/vite.config.js:/app/vite.config.js
    # env_file:
    #   - .env
    depends_on:
      - backend
## BACKEND CONTAINER
  backend:
    container_name: transcendence-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    volumes:
    #   - ./backend/src:/app/src
      - ./backend/src/database:/app/database
    env_file:
      - .env
    command: npm start
    # networks:
      # - app-network


# networks:
#   app-network:
#     driver: bridge
# volumes:
#   transcendence-db:
#       driver: local
